---@mod rocks_treesitter.ft_parser_map
---@brief [[
---
---Default file types to parser maps for filetypes
---whose names do not match the parser names.
---
---@brief ]]

return {
    PKGBUILD = "bash",
    pacscript = "bash",
    ["html.handlebars"] = "glimmer",
    ["typescript.tsx"] = "tsx",
    apkbuild = "bash",
    asm68k = "m68k",
    automake = "make",
    bib = "bibtex",
    bzl = "starlark",
    cls = "latex",
    confini = "ini",
    cs = "c_sharp",
    dosini = "ini",
    dsp = "faust",
    dts = "devicetree",
    ecma = "javascript",
    eelixir = "eex",
    eruby = "embedded_template",
    expect = "tcl",
    fsd = "facility",
    gdresource = "godot_resource",
    gdshaderinc = "gdshader",
    gitconfig = "git_config",
    gitdiff = "diff",
    gitrebase = "git_rebase",
    handlebars = "glimmer",
    haskellpersistent = "haskell_persistent",
    html_tags = "html",
    janet = "janet_simple",
    javascriptreact = "javascript",
    jproperties = "properties",
    jsx = "javascript",
    ld = "linkerscript",
    list = "commonlisp",
    mysqp = "sqp",
    neomuttrc = "muttrc",
    ocamlinterface = "ocaml_interface",
    pandoc = "markdown",
    poefilter = "poe_filter",
    qml = "qmljs",
    quarto = "markdown",
    rmd = "markdown",
    sbt = "scala",
    sface = "surface",
    sh = "bash",
    shaderslang = "slang",
    sshconfig = "ssh_config",
    sty = "latex",
    svg = "xml",
    systemverilog = "verilog",
    sysverilog = "verilog",
    tal = "uxntal",
    tape = "vhs",
    tex = "latex",
    tla = "tlaplus",
    trace32 = "t32",
    ts = "typescript",
    typescriptreact = "tsx",
    udevrules = "udev",
    vlang = "v",
    xsd = "xml",
    xslt = "xml",
}
